In [5]:
import pandas as pd

In [6]:
# 1. Carregando a base de dados indicando o separador correto (ponto e vírgula)
df = pd.read_csv('/CHURN_TELECON_MOD08_TAREFA.csv', sep=';')
# 2. Mostrando as 5 primeiras linhas da tabela para ver se carregou certinho
display(df.head())
# 3. Verificando o tipo de dado de cada coluna
df.info()

,customerID,Genero,Idoso,Casado,Dependents,Tempo_como_Cliente,PhoneService,Servico_Internet,Servico_Seguranca,Suporte_Tecnico,StreamingTV,Tipo_Contrato,PaymentMethod,Pagamento_Mensal,Total_Pago,Churn
0,7590-VHVEG,Female,0,Yes,No,1,No,DSL,No,No,No,Month-to-month,Electronic check,29.85,29.85,No
1,5575-GNVDE,Male,0,No,No,34,Yes,DSL,Yes,No,No,One year,Mailed check,56.95,1889.50,No
2,3668-QPYBK,Male,0,No,No,2,Yes,DSL,Yes,No,No,Month-to-month,Mailed check,53.85,108.15,Yes
3,7795-CFOCW,Male,0,No,No,45,No,DSL,Yes,Yes,No,One year,Bank transfer (automatic),NaN,1840.75,No
4,9237-HQITU,NaN,0,No,No,2,Yes,Fiber optic,No,No,No,Month-to-month,Electronic check,NaN,151.65,Yes

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2500 entries, 0 to 2499
Data columns (total 16 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   customerID          2500 non-null   object
 1   Genero              2488 non-null   object
 2   Idoso               2500 non-null   int64
 3   Casado              2500 non-null   object
 4   Dependents          2500 non-null   object
 5   Tempo_como_Cliente  2500 non-null   int64
 6   PhoneService        1018 non-null   object
 7   Servico_Internet    2500 non-null   object
 8   Servico_Seguranca   2500 non-null   object
 9   Suporte_Tecnico     2500 non-null   object
 10  StreamingTV         2500 non-null   object
 11  Tipo_Contrato       2500 non-null   object
 12  PaymentMethod       2500 non-null   object
 13  Pagamento_Mensal    2175 non-null   float64
 14  Total_Pago          2500 non-null   float64
 15  Churn               2495 non-null   object
dtypes: float64(2), int64(2), object(12)
memory usage: 312.6+ KB

In [7]:
# 1. Alterando o tipo de dado da coluna 'Idoso' de número inteiro para texto
df['Idoso'] = df['Idoso'].astype(str)
# 2. Verificando novamente para confirmar se a mudança aconteceu
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2500 entries, 0 to 2499
Data columns (total 16 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   customerID          2500 non-null   object
 1   Genero              2488 non-null   object
 2   Idoso               2500 non-null   object
 3   Casado              2500 non-null   object
 4   Dependents          2500 non-null   object
 5   Tempo_como_Cliente  2500 non-null   int64
 6   PhoneService        1018 non-null   object
 7   Servico_Internet    2500 non-null   object
 8   Servico_Seguranca   2500 non-null   object
 9   Suporte_Tecnico     2500 non-null   object
 10  StreamingTV         2500 non-null   object
 11  Tipo_Contrato       2500 non-null   object
 12  PaymentMethod       2500 non-null   object
 13  Pagamento_Mensal    2175 non-null   float64
 14  Total_Pago          2500 non-null   float64
 15  Churn               2495 non-null   object
dtypes: float64(2), int64(1), object(13)
memory usage: 312.6+ KB

In [10]:
# 1. Contando quantos dados estão faltando (nulos) em cada coluna
valores_ausentes = df.isnull().sum()
# 2. Calculando o percentual de dados faltantes (quantidade de nulos dividida pelo total de linhas, multiplicando por 100)
percentual_ausentes = (df.isnull().sum()/len(df)) * 100
# 3. Juntando as duas informações em uma tabelinha bonita para visualização
tabela_nulos = pd.DataFrame({'Valores Ausentes': valores_ausentes, 'Percentual (%)': percentual_ausentes})
# 4. Mostrando a tabelateF na tela, ornadenada do maior problema para o menor
display(tabela_nulos.sort_values(by='Percentual (%)', ascending=False))

                    Valores Ausentes  Percentual (%)
PhoneService                    1482           59.28
Pagamento_Mensal                 325           13.00
Genero                            12            0.48
Churn                              5            0.20
Casado                             0            0.00
Dependents                         0            0.00
Idoso                              0            0.00
customerID                         0            0.00
Servico_Internet                   0            0.00
Tempo_como_Cliente                 0            0.00
Servico_Seguranca                  0            0.00
Suporte_Tecnico                    0            0.00
Tipo_Contrato                      0            0.00
StreamingTV                        0            0.00
PaymentMethod                      0            0.00
Total_Pago                         0            0.00

In [13]:
# 1. Excuindo a coluna 'PhoneService' inteira por ter quase 60% de dados ausentes
df = df.drop(columns=['PhoneService'])
# 2. Excluindo apenas as linhas onde a coluna 'Churn' está vazia
df = df.dropna(subset=['Churn'])
# 3. Verificando o tamanho da tabela após as exclusões
print(f"Tamanho da base atual:{df.shape}")

Tamanho da base atual:(2495, 15)

In [15]:
# 1. Preenchendo os valores do 'Pagamento_Mensal' com MEDIANA
mediana_pagamento = df['Pagamento_Mensal'].median()
df['Pagamento_Mensal'].fillna(mediana_pagamento, inplace=True)
# 2. Preenchendo os valores do 'Genero' com a MODA
moda_genero = df['Genero'].mode()[0]
df['Genero'].fillna(moda_genero, inplace=True)
# 3. Fazendo o 'Raio-X' final para garantir que não há mais nenhum dado vazio na tabela
print(df.isnull().sum())

customerID            0
Genero                0
Idoso                 0
Casado                0
Dependents            0
Tempo_como_Cliente    0
Servico_Internet      0
Servico_Seguranca     0
Suporte_Tecnico       0
StreamingTV           0
Tipo_Contrato         0
PaymentMethod         0
Pagamento_Mensal      0
Total_Pago            0
Churn                 0
dtype: int64

/tmp/ipykernel_2100/2309653512.py:3: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['Pagamento_Mensal'].fillna(mediana_pagamento, inplace=True)

In [17]:
# 1. Padronizando a coluna 'Genero'
# Tudo o que for 'F' ou 'f' vira 'Female', e o que for 'M' vira 'Male'
df['Genero'] = df['Genero'].replace({'F':'Female','f':'Female', 'M': 'Male'})
# 2. Padronizando a coluna 'Servico_Internet'
# Tudo o que for 'dsl' minúsculo vira 'DSL' maiúsculo
df['Servico_Internet'] = df['Servico_Internet'].replace({'dsl':'DSL'})
# 3. Verificando se os valores únicos ficaram limpos
print("Valores únicos em Gênero:", df['Genero'].unique())
print("Valores únicos em Internet:", df['Servico_Internet'].unique())
df

Valores únicos em Gênero: ['Female' 'Male']
Valores únicos em Internet: ['DSL' 'Fiber optic' 'No']

,customerID,Genero,Idoso,Casado,Dependents,Tempo_como_Cliente,Servico_Internet,Servico_Seguranca,Suporte_Tecnico,StreamingTV,Tipo_Contrato,PaymentMethod,Pagamento_Mensal,Total_Pago,Churn
0,7590-VHVEG,Female,0,Yes,No,1,DSL,No,No,No,Month-to-month,Electronic check,29.85,29.85,No
1,5575-GNVDE,Male,0,No,No,34,DSL,Yes,No,No,One year,Mailed check,56.95,1889.50,No
2,3668-QPYBK,Male,0,No,No,2,DSL,Yes,No,No,Month-to-month,Mailed check,53.85,108.15,Yes
3,7795-CFOCW,Male,0,No,No,45,DSL,Yes,Yes,No,One year,Bank transfer (automatic),71.45,1840.75,No
4,9237-HQITU,Male,0,No,No,2,Fiber optic,No,No,No,Month-to-month,Electronic check,71.45,151.65,Yes
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2495,6188-UXBBR,Female,0,Yes,No,38,No,No internet service,No internet service,No internet service,One year,Credit card (automatic),20.25,814.75,No
2496,2333-KWEWW,Male,0,No,No,18,No,No internet service,No internet service,No internet service,Two year,Credit card (automatic),20.05,388.60,No
2497,5702-SKUOB,Female,0,Yes,No,4,No,No internet service,No internet service,No internet service,Month-to-month,Mailed check,19.60,93.45,No
2498,1134-YWTYF,Male,0,Yes,No,27,DSL,No,Yes,No,Month-to-month,Electronic check,53.80,1389.85,No
2499,6061-GWWAV,Male,0,No,Yes,41,DSL,Yes,No,Yes,One year,Mailed check,70.20,2894.55,No

In [18]:
# 1. Renomeando as colunas para o Português e padrão snake_case
df = df.rename(columns={
    'customerID': 'id_cliente',
    'Genero': 'genero',
    'Idoso': 'idoso',
    'Casado': 'casado',
    'Dependents': 'dependentes',
    'Tempo_como_Cliente': 'tempo_como_cliente',
    'Servico_Internet': 'servico_internet',
    'Servico_Seguranca': 'servico_seguranca',
    'Suporte_Tecnico': 'suporte_tecnico',
    'StreamingTV': 'streaming_tv',
    'Tipo_Contrato': 'tipo_contrato',
    'PaymentMethod': 'metodo_pagamento',
    'Pagamento_Mensal': 'pagamento_mensal',
    'Total_Pago': 'total_pago',
    'Churn': 'churn'
})

# 2. Exibindo as 5 primeiras linhas para vermos a tabela final, pronta e bonita!
display(df.head())

,id_cliente,genero,idoso,casado,dependentes,tempo_como_cliente,servico_internet,servico_seguranca,suporte_tecnico,streaming_tv,tipo_contrato,metodo_pagamento,pagamento_mensal,total_pago,churn
0,7590-VHVEG,Female,0,Yes,No,1,DSL,No,No,No,Month-to-month,Electronic check,29.85,29.85,No
1,5575-GNVDE,Male,0,No,No,34,DSL,Yes,No,No,One year,Mailed check,56.95,1889.50,No
2,3668-QPYBK,Male,0,No,No,2,DSL,Yes,No,No,Month-to-month,Mailed check,53.85,108.15,Yes
3,7795-CFOCW,Male,0,No,No,45,DSL,Yes,Yes,No,One year,Bank transfer (automatic),71.45,1840.75,No
4,9237-HQITU,Male,0,No,No,2,Fiber optic,No,No,No,Month-to-month,Electronic check,71.45,151.65,Yes